### ISSUE TITLE
Build fails against ADSv18 due to missing definition

### ISSUE THREAD

**Issue by nmaytan** [Cosylab/adsDriver#4]
As of [1ec463c](https://github.com/Beckhoff/ADS/commit/1ec463cf3d991dc7f772d840a869d012278350a9) in the ADS library (included in the v18 release), building adsDriver will fail due to a missing definition for `CONFIG_DEFAULT_LOGLEVEL`:

```
../../../adsApp/src/beckhoffAdsLib/AdsLib/Log.cpp:27:27: error: ‘CONFIG_DEFAULT_LOGLEVEL’ was not declared in this scope
 size_t Logger::logLevel = CONFIG_DEFAULT_LOGLEVEL;
```

I worked around this by adding a define directive `USR_CXXFLAGS += -DCONFIG_DEFAULT_LOGLEVEL=1` in `adsApp/src/Makefile` & seemed to build successfully, but I'm not sure this is the best/preferred practice.

**Comment by jevarlec** [comment]
Thanks for bringing this to our attention, we'll fix this ASAP.

**Comment by jevarlec** [comment]
Just out of curiosity, what was the reason you changed the submodule commit to the newer? Did you experience any problems, or was it because you prefer to have the latest version?

**Comment by nmaytan** [comment]
That's a fair question! We didn't have any problems with the earlier version, we just decided to skip straight ahead and pull the latest tags we could at the time. In the worst case, we'd hopefully catch something slightly useful (like this issue). 

We've had v18 working seemingly fine on RHEL8 now (though we haven't done anything "complicated" yet), but will revert to v17 for our internal RPM until your next release. (:
