### ISSUE TITLE
Readback of output variables after iocInit

### ISSUE THREAD

**Issue by redpiramide** [Cosylab/adsDriver#6]
With the current available operation modes, it is possible to exclusively read or write a variable, but there is no support for readback of output variables. 

In my use case it is possible that setpoints in the plc get changed manually by a local touch panel, the internal logic or by an opc-ua connection to another plc. The changed setpoints should synchronize back to epics to keep consistency. 

To not affect the current operation modes, adding a new mode called `RW` or to add `info(asyn:READBACK, "1")` to the record definition may be an option. These records are included in the cyclic `SumRead` but also allow writing them on request.

See the discussion on the EPICS Tech Talk for Reference:
https://epics.anl.gov/tech-talk/2024/msg00522.php

**Comment by Synthetica9** [comment]
We're having the same issue, similar with #7

**Comment by exzombie** [comment]
Thank you for the feedback. I'll take a look at the first opportunity. As noted in the linked discussion, there's a chance that this issue can be more easily solved than #7 and would be sufficient as a workaround for #7 in cases where a short window of UDF after initialization is acceptable.

**Comment by redpiramide** [comment]
Please take a look at my fork. I have managed to get the readback, but still testing edge cases. I can also open a pull request.
